version: '3'

services:
  notebook:
    image: jupyter/pyspark-notebook
    volumes:
      - $PWD:/home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_LAB_ENABLE=yes
    command: "start.sh jupyter lab"